<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.044" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2016-07-03T20:49:40" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="UserController" timestamp="2016-07-03T20:49:40" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="#login()" timestamp="2016-07-03T20:49:40" tests="1" failures="1" time="0.044">
    <testcase name="Root Suite UserController #login() should redirect to /mypage" time="0.044" classname="should redirect to /mypage">
      <failure><![CDATA[Error: expected 302 "Found", got 404 "Not Found"
    at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
    at Test.assert (node_modules/supertest/lib/test.js:148:18)
    at Server.assert (node_modules/supertest/lib/test.js:127:12)
    at emitCloseNT (net.js:1514:8)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="UserModel" timestamp="2016-07-03T20:49:40" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="#find()" timestamp="2016-07-03T20:49:40" tests="1" failures="1" time="0">
    <testcase name="Root Suite UserModel #find() should check find function" time="0" classname="should check find function">
      <failure><![CDATA[ReferenceError: User is not defined
    at Context.<anonymous> (test/integration/models/User.test.js:4:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>